New-VDPortgroup -VDSwitch INF_VDS_Production -name ConPac-VLAN-2717 -vlanid 2717
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-293 -vlanid 293
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-297 -vlanid 297
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-300 -vlanid 300
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-4067 -vlanid 4067
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-4068 -vlanid 4068
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-4069 -vlanid 4069
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-4070 -vlanid 4070
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-4071 -vlanid 4071
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-4072 -vlanid 4072
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-4080 -vlanid 4080
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-4081 -vlanid 4081
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-4082 -vlanid 4082
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-4083 -vlanid 4083
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-4084 -vlanid 4084
New-VDPortgroup -VDSwitch INF_VDS_Production -name Data-VLAN-4085 -vlanid 4085
New-VDPortgroup -VDSwitch INF_VDS_Production -name Mgmt-VLAN-982 -vlanid 982
New-VDPortgroup -VDSwitch INF_VDS_Production -name vCenter-VLAN-2713 -vlanid 2713
New-VDPortgroup -VDSwitch INF_VDS_Production -name vMotion-VLAN-2715 -vlanid 2715
New-VDPortgroup -VDSwitch INF_VDS_Production -name ServiceCon-VLAN-2714 -vlanid 2714